### ISSUE TITLE
Dreamcast Timing Value

### ISSUE THREAD

**Issue by ghost** [ArtemioUrbina/240pTestSuite#2]
Hi!

I've been using 240p Test Suite for ages and it's been one of my favorite utilities.

I think I've discovered a bug, however, which you can see here:
https://github.com/ArtemioUrbina/240pTestSuite/blob/master/240psuite/Dreamcast/PVR/vmodes.c#L359

`data = 0x03 | 0x3f << 8 | 0x319 << 12 | 0x0f << 22;`

Should be:

`data = 0x03 << 8 | 0x3f | 0x319 << 12 | 0x0f << 22;`

The reason I believe this to be a bug is because I was looking at a disassembly of my own Dreamcast BootROM (BIOS), and saw that it uses a value of 0x03f1933f.

By the same token, I think all of the regs[0x38] assignments in vmodes.c have that << 8 in the wrong place. This may be the underlying cause for your note that states that US Dreamcasts corrupt a PAL signal; they should not as they all have the same video hardware. It's just some region parameters in the internal flash memory that differ between the models.

480i NTSC looks like it should be 0x07d6c63f
576i PAL looks like it should be 0x07d6a53f

**Comment by ArtemioUrbina** [comment]
It seems you are right, I will be able to test it soon, but not immediately since I'm working on several
things related to the suite. MDfourier, mainly, on the NES and SNES. I need to swap to this with my full attention to check the timings on the scope for every video mode and confirm what you say about PAL

I already took the appropriate notes, this is very welcome.

If I compiled a binary, which would be fast on my side, would you be able to test it? There is no rush of course, I just don't want this hanging in my to do list too long. 

If not, I will just take care of it for the next release, no worries.

Again, thanks a lot for your message and finding this out. Just wanted to confirm I received it
and checked it, at least superficially, atm.

**Comment by Moopthehedgehog** [comment]
I can test, no problem. It also seems I was wrong about some aspects about the video output hardware, as I discovered when trying to shove a PAL signal out through my NTSC machine...
https://bordersdown.net/threads/70904-Change-your-Dreamcast-s-region
(So I can't test PAL stuff, apparently)

**Comment by ArtemioUrbina** [comment]
Excellent, thank you Here is a build with the changes you proposed

https://we.tl/t-4C2SVM0KEg

Please let me know how it goes.

**Comment by Moopthehedgehog** [comment]
VGA and NTSC are good as far as I can tell. Granted, these are the values that the BIOS uses, after all, so we should hope so :)

I did also notice some other things I'm not sure about:
I see 172 is used both here and in KOS for 640x480 VGA, however the BIOS uses 168. Actually, both KOS and this project do a number of things that are just slightly off from what the BIOS does. That sync discrepancy was just the most obvious one. The other ones appear to be mostly just screen positioning values that are off by small quantities.

**Comment by ArtemioUrbina** [comment]
Thank you, sure you can contact me whenever you want. I'll leave this issue open until I can check the values myself in a scope, hopefully this week.

**Comment by Moopthehedgehog** [comment]
Well, I found a way to examine PAL modes, so here it is:
https://github.com/Moopthehedgehog/DreamHAL/blob/master/startup/startup_support.c
The function of interest is "STARTUP_Set_Video"

**Comment by ArtemioUrbina** [comment]
I added them to the Suite, but they've not been released since I have more changes in queue
