### ISSUE TITLE
Minor visual issue with Dreamcast v.2.03

### ISSUE THREAD

**Issue by MoeFoh** [ArtemioUrbina/240pTestSuite#30]
Controller Test.
Pressing Start + Right d-pad (which I did by accident, meant Start + Left d-pad to exit) resulted in this screen:
![240p-controller-test-bug-dreamcast_v2 03](https://github.com/ArtemioUrbina/240pTestSuite/assets/96657677/53b83fcc-c4ec-44e3-983d-c87585ff06b2)
I guess this a normal feature? So not really an issue. Kind of hard to read in gray on my monitor.

**Comment by ArtemioUrbina** [comment]
Thank you for caring.

Yes, as you mention, it is a documented feature.

As detailed in the help text that you can access in all tests:

"The test only shows the reported controller functions by default, but by pressing Right+Start you can display all possible inputs in order to  test some non-compliant implementations or 
duplicated outputs, like some light guns."

Take care
