### ISSUE TITLE
Issue building wii version on Linux

### ISSUE THREAD

**Issue by HeroponRikiBestest** [ArtemioUrbina/240pTestSuite#5]
Attempting to run `make` in `240pTestSuite/240psuite/Wii/240pSuite` results in 
`textures.scf`
`make[1]: *** [/opt/devkitpro/devkitPPC/wii_rules:25: textures.tpl] Segmentation fault (core dumped)`
`make: *** [Makefile:105: build] Error 2`

If it matters, this was built on Linux Mint 20, using the devkitpro package obtained [here](https://github.com/devkitPro/pacman/releases/tag/v1.0.2)

**Comment by ArtemioUrbina** [comment]
Hello, thanks for reporting this. I looked into it by installing a clean VM and used the binaries provided from the site. 

The issue is within devkitpro itself, since the gxtexconv toopl crashes when it has more than 20 textures.

I created a pull request with the patch to fix gxtexconv. Here is the pull request and patch if you want to apply it and use it meanwhile: https://github.com/devkitPro/gamecube-tools/pull/3

Also as a note, you will need to install the following in your setup:

sudo dkp-pacman -S ppc-zlib
sudo dkp-pacman -S ppc-mxml 

Also please go into the tools folder and run:
gcc cfile.c -o cfile -lz

After that you will be able to compile it without issues, given you have a patched gxtexconv.

**Comment by HeroponRikiBestest** [comment]
Ah, sorry about that. Thank you for fixing the issue! I don't see a cfile.c in devkitpro/tools or /devkitpro/tools/bin, though.

**Comment by ArtemioUrbina** [comment]
> Ah, sorry about that. Thank you for fixing the issue!

No problem! It was awesome that the devkitpro team accepted the patch already. Thanks for reporting it.
